# Generated by Django 3.1.3 on 2021-01-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CookIT', '0002_auto_20210109_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_file',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
